name: Kubernetes Plugin
description: Kubernetes plugin will allow you to create new pods remotely from a Clarive instance.
version: 1.0
icon: https://cdn.rawgit.com/clarive/cla-kubernetes-plugin/master/public/icon/kubernetes.svg?sanitize=true
url: https://github.com/clarive/cla-kubernetes-plugin
requires:
  - clarive_version: 6.8 <= version
dependencies:
  - cla-kubernetes-plugin
